goal: [2.7, 0.0]
initial_actor_positions: [[-5.0, 0.0, 0.05]]
device: "cpu"
dt: 0.1
steps: 200

mppi: 
  device: "cpu"
  mppi_mode: "simple"  # halton-spline, simple
  sampling_method: "halton"   # halton, random
  num_samples: 300
  horizon: 50                 # At least 12 for Halton Sampling
  lambda_: 0.1
  u_min: [-1.5]
  u_max: [1.5]
  noise_sigma: [[0.5, 0.], [0., 0.5]]
  update_lambda: True
  rollout_var_discount: 0.95
  sample_null_action: True
  noise_abs_cost: False
  filter_u: True

simulator:
  urdf: "jackal.urdf"
  mode: "vel"
  render: True
